// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGv81o0LALLH4OR4tcAyIr-hZoBc6LNbA',
    appId: '1:391681745345:web:bc88de1f15e2303366cf40',
    messagingSenderId: '391681745345',
    projectId: 'toolmato-9552a',
    authDomain: 'toolmato-9552a.firebaseapp.com',
    storageBucket: 'toolmato-9552a.appspot.com',
    measurementId: 'G-V7DHMYFBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJAtqYkn7WIYm1MJ8je5JxmlyT8yVLMXk',
    appId: '1:391681745345:android:fa0fbd88f4c1f7d266cf40',
    messagingSenderId: '391681745345',
    projectId: 'toolmato-9552a',
    storageBucket: 'toolmato-9552a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXyT5U503hmbSgmvUKwodMY9a0EOsIdsI',
    appId: '1:391681745345:ios:bf8ca4e7203158c466cf40',
    messagingSenderId: '391681745345',
    projectId: 'toolmato-9552a',
    storageBucket: 'toolmato-9552a.appspot.com',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXyT5U503hmbSgmvUKwodMY9a0EOsIdsI',
    appId: '1:391681745345:ios:bf8ca4e7203158c466cf40',
    messagingSenderId: '391681745345',
    projectId: 'toolmato-9552a',
    storageBucket: 'toolmato-9552a.appspot.com',
    iosBundleId: 'com.example.pomodoro',
  );
}
